# The admission webhook only validates ScaledObjects on creation, so drop it to save a pod.
webhooks:
  enabled: false

resources:
  operator:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 300Mi
  metricServer:
    requests:
      cpu: 50m
      memory: 100Mi
    limits:
      memory: 300Mi
