{{- if .Values.gateway.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-app
  labels:
    {{- include "mathboard.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
  hostnames:
    - {{ .Values.gateway.appHost | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Release.Name }}-frontend
          port: {{ .Values.frontend.port }}
          weight: 1
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ .Release.Name }}-api
  labels:
    {{- include "mathboard.labels" . | nindent 4 }}
spec:
  parentRefs:
    - group: gateway.networking.k8s.io
      kind: Gateway
      name: {{ .Values.gateway.name }}
  hostnames:
    - {{ .Values.gateway.apiHost | quote }}
  rules:
    - matches:
        - path:
            type: PathPrefix
            value: /
      timeouts:
        request: 0s
      backendRefs:
        - group: ""
          kind: Service
          name: {{ .Release.Name }}-backend
          port: {{ .Values.backend.port }}
          weight: 1
{{- end }}
