apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: mathboard-db
  namespace: default
spec:
  instances: 1
  imageName: ghcr.io/cloudnative-pg/postgresql:17
  storage:
    size: 2Gi
  postgresql:
    parameters:
      max_connections: "200"
  resources:
    requests:
      cpu: 200m
      memory: 512Mi
    limits:
      memory: 1Gi
  bootstrap:
    initdb:
      database: mathboard
      owner: mathboard
